units:
  kx: cx
  ky: cy

  px: kx + 2
  py : ky + 2

  $default_width: cx
  $default_height: cy

points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx

      anchor:
        shift: [100, -100]

      columns:
        outer:
          rows.thumb.skip: true
          key.column_net: P21
        pinky:
          rows.thumb.skip: true
          key.column_net: P10
        ring:
          rows.thumb.skip: true
          key.stagger: 3
          key.column_net: P16
        middle:
          key.stagger: 3
          key.column_net: P14
          
        index:
          key.stagger: -3
          key.column_net: P19
        inner:
          key.stagger: -2 
          key.column_net: P20
      rows:
        under:
          row_net: P4
        middle:
          row_net: P3
        upper:
          row_net: P2
    thumbs:
      key:
        padding: 1ky
        spread: 1.1px
      anchor:
        ref: matrix_inner_under
        shift: [-1.5kx, -1.4ky]
      columns:
        left:
          key.splay: -10
          key.column_net: P10
          
        mid:
          key.splay: -15
          key.column_net: P16
        right:
          key.splay: -15
          key.shift: [0, -2]
          key.column_net: P14
      rows:
        row:
          row_net: P5
  mirror: &mirror
    ref: matrix_inner_upper
    distance: 4kx

outlines:
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5,ky-0.5]
  board_left:
    - what: polygon
      operation: stack
      points:

      # Bottom
      - ref: matrix_outer_under
        shift: [-12, -12]

      - ref: thumbs_left_row
        shift: [-15, 9]
      - ref: thumbs_left_row
        shift: [-12, -11]


     
      - ref: thumbs_right_row
        shift: [12, -12]
      - ref: thumbs_right_row
        shift: [12, 12]
      - ref: thumbs_right_row
        shift: [-11, 39]

      
      - ref: matrix_inner_middle
        shift: [30, 0]
      
      - ref: matrix_inner_middle
        shift: [12, 0]

      
      # Top
      - ref: matrix_inner_upper
        shift: [12, 0.6py]

      - ref: matrix_middle_upper
        shift: [7, 13]
      - ref: matrix_middle_upper
        shift: [-7, 13]

      - ref: matrix_outer_upper
        shift: [-12, 12]
      fillet: 2

  board_right:
    - what: polygon
      operation: stack
      points:

      # Bottom
      - ref: mirror_matrix_outer_under
        shift: [-12, -12]

      - ref: mirror_thumbs_left_row
        shift: [-15, 9]
      - ref: mirror_thumbs_left_row
        shift: [-12, -11]


     
      - ref: mirror_thumbs_right_row
        shift: [12, -12]
      - ref: mirror_thumbs_right_row
        shift: [12, 12]
      - ref: mirror_thumbs_right_row
        shift: [-11, 39]

      
      - ref: mirror_matrix_inner_middle
        shift: [30, 0]
      
      - ref: mirror_matrix_inner_middle
        shift: [12, 0]

      
      # Top
      - ref: mirror_matrix_inner_upper
        shift: [12, 0.6py]

      - ref: mirror_matrix_middle_upper
        shift: [7, 13]
      - ref: mirror_matrix_middle_upper
        shift: [-7, 13]

      - ref: mirror_matrix_outer_upper
        shift: [-12, 12]
      fillet: 2



  combo_left:
    - name: board_left
    - operation: subtract
      name: keys
  
  combo_right:
    - name: board_right
    - operation: subtract
      name: keys

  combo_both:
    - name: combo_right
    - operation: add
      name: combo_left

pcbs:
  left:
    outlines:
      main:
        outline: board_left
    footprints:
      choc_hotswap:
        what: choc
        where: /^((matrix_.*)|(thumbs_.*))/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^((matrix_.*)|(thumbs_.*))/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: thumbs_right_row
          shift: [-18.5,33]
          rotate: -50

      # Battery jack
      jstph:
        what: jstph
        where:
          ref: thumbs_mid_row
          shift: [-7, 13]
          rotate: 115
        params:
            side: B
            pos: pos
            neg: GND

      horizontal_reset:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: thumbs_right_row
          shift: [6.5, 15]
          rotate: -50

      battery_switch:
        what: slider
        where:
            ref: thumbs_right_row
            shift: [1.5, 21.6]
            rotate: -50
        params:
            side: B
            from: pos
            to: RAW

      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: thumbs_mid_row
          shift: [4, 17]

      hole_bottom_left:
        what: mountinghole
        where:
          ref: thumbs_left_row
          shift: [-5, 13]

      hole_bottom_mid:
        what: mountinghole
        where:
          ref: thumbs_mid_row
          shift: [0, -13]

      hole_top_left:
        what: mountinghole
        where:
          ref: matrix_pinky_upper
          shift: [-2, 12]

      hole_top_right:
        what: mountinghole
        where:
          ref: matrix_index_upper
          shift: [-3, 11]

      hole_bottom_left_left:
        what: mountinghole
        where:
          ref: matrix_outer_under
          shift: [-8, -8]

      hole_bottom_right_right:
        what: mountinghole
        where:
          ref: thumbs_right_row
          shift: [-6, 15]

  right:
    outlines:
      main:
        outline: board_right
    footprints:
      choc_hotswap:
        what: choc
        where: /^((mirror_matrix_.*)|(mirror_thumbs_.*))/
        params:
          keycaps: true
          reverse: false
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: diode
        where: /^((mirror_matrix_.*)|(mirror_thumbs_.*))/
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      promicro:
        what: promicro
        params:
          orientation: "down"
        where:
          ref: mirror_thumbs_right_row
          shift: [-18.5,33]
          rotate: 130

      # Battery jack
      jstph:
        what: jstph
        where:
          ref: mirror_thumbs_mid_row
          shift: [-7, 13]
          rotate: 115
        params:
            side: B
            pos: pos
            neg: GND

      horizontal_reset:
        what: EVQPUC
        params: 
          side: B
          from: GND
          to: RST 
        where:
          ref: mirror_thumbs_right_row
          shift: [6.5, 15]
          rotate: -50

      battery_switch:
        what: slider
        where:
            ref: mirror_thumbs_right_row
            shift: [1.5, 21.6]
            rotate: -50
        params:
            side: B
            from: pos
            to: RAW

      # Mounting holes
      hole_bottom_right:
        what: mountinghole
        where:
          ref: mirror_thumbs_mid_row
          shift: [4, 17]

      hole_bottom_left:
        what: mountinghole
        where:
          ref: mirror_thumbs_left_row
          shift: [-5, 13]

      hole_bottom_mid:
        what: mountinghole
        where:
          ref: mirror_thumbs_mid_row
          shift: [0, -13]

      hole_top_left:
        what: mountinghole
        where:
          ref: mirror_matrix_pinky_upper
          shift: [-2, 12]

      hole_top_right:
        what: mountinghole
        where:
          ref: mirror_matrix_index_upper
          shift: [-3, 11]

      hole_bottom_left_left:
        what: mountinghole
        where:
          ref: mirror_matrix_outer_under
          shift: [-8, -8]

      hole_bottom_right_right:
        what: mountinghole
        where:
          ref: mirror_thumbs_right_row
          shift: [-6, 15]
